#!/usr/bin/env python3
# --- START OF FILE Validator.py ---

import os
import re
import yaml
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List, Tuple
import sys

# --- CRITICAL FIX START: Conditional import for vault_utils ---
if __name__ == "__main__":
    _scripts_dir = Path(__file__).parent.resolve() # This is the directory containing Validator.py
    if str(_scripts_dir) not in sys.path:
        sys.path.insert(0, str(_scripts_dir))
    
    _parent_dir = _scripts_dir.parent.resolve() # This is ~/code/python/scripts/
    if str(_parent_dir) not in sys.path:
        sys.path.insert(0, str(_parent_dir))

    try:
        import vault_utils 
    except ImportError:
        import obsidian_automation.vault_utils as vault_utils
else:
    from . import vault_utils
# --- CRITICAL FIX END ---

# ===========================
# CONFIG
# ===========================
# Define expected H1 headings for different note types and their strict order
EXPECTED_H1_SECTIONS = {
    "Unit": [
        "Overview",
        "Learning Objectives",
        "Unit Applications & Real-World Relevance",
        "Active Learning Prompts",
        "Unit Challenges & Common Misconceptions",
        "Connections",
        "Next Steps for Deeper Understanding",
        "Possible Questions"
    ],
    "Foundational": [
        "Definition",
        "Formal Notation & Syntax",
        "Detailed Explanation",
        "Why It's Important & Where You'll See It",
        "Trade-offs & Common Pitfalls",
        "Knowledge Graph Connections",
        "Key Takeaways"
    ],
    "Core": [
        "Definition",
        "Formal Notation & Syntax",
        "Detailed Explanation",
        "Why It's Important & Where You'll See It",
        "Trade-offs & Common Pitfalls",
        "Knowledge Graph Connections",
        "Key Takeaways"
    ],
    "Supporting": [
        "Definition",
        "Formal Notation & Syntax",
        "Detailed Explanation",
        "Why It's Important & Where You'll See It",
        "Trade-offs & Common Pitfalls",
        "Knowledge Graph Connections",
        "Key Takeaways"
    ],
    "Questions": [
        "Questions" # The unit hub title should be part of this H1, but for order we check this.
    ],
    "MOC": [ # For MOCs generated by Indexer
        "Years", # For Computer_Science_MOC
        "Semesters", # For Year_II_MOC
        "Courses", # For Year_II_Semester_I_MOC
        "Hubs" # For Computer_Programming_MOC
    ]
}

# ===========================
# VALIDATION HELPER FUNCTIONS
# ===========================

def _validate_single_markdown_table(table_lines: List[str], note_title: str, table_start_line_in_body: int) -> List[str]:
    """
    Validates the structure and formatting of a single Markdown table block.
    `table_start_line_in_body` is the line number where the table begins *within the body_content*.
    """
    table_errors: List[str] = []

    if len(table_lines) < 2:
        table_errors.append(f"Table in '{note_title}' at body line {table_start_line_in_body + 1}: Table is too short (needs at least header and separator).")
        return table_errors

    # Extract header and separator, assuming they are the first two lines
    header_line_str = table_lines[0] # CRITICAL FIX: Access list elements directly
    separator_line_str = table_lines[1] # CRITICAL FIX: Access list elements directly

    # 1. Basic check for pipes
    if not (header_line_str.strip().startswith('|') and header_line_str.strip().endswith('|') and
            separator_line_str.strip().startswith('|') and separator_line_str.strip().endswith('|')):
        table_errors.append(f"Table in '{note_title}' at body line {table_start_line_in_body + 1}: Missing outer pipes in header or separator. Header: '{header_line_str.strip()}', Separator: '{separator_line_str.strip()}'.")
        # Attempt to proceed by forcing pipe splitting for subsequent checks
        header_parts = [h.strip() for h in header_line_str.split('|')]
        separator_parts = [s.strip() for s in separator_line_str.split('|')]
    else:
        header_parts = [h.strip() for h in header_line_str.split('|')]
        separator_parts = [s for s in separator_line_str.split('|')] # Don't strip separators yet for proper alignment check

    # Filter out empty strings from split (due to leading/trailing pipes)
    headers = [h for h in header_parts if h]
    separators = [s for s in separator_parts if s.strip()] # Strip here for length check

    if len(headers) != len(separators):
        table_errors.append(f"Table in '{note_title}' at body line {table_start_line_in_body + 1}: Mismatched number of headers ({len(headers)}) and separator columns ({len(separators)}).")
        return table_errors # Cannot proceed reliably with column-specific checks

    num_columns = len(headers)
    
    # 2. Check separator format (---, :---, ---:, :---:)
    alignment_types = []
    min_column_visual_widths = [len(h) for h in headers] # Start with header width
    
    for col_idx, sep in enumerate(separators):
        stripped_sep = sep.strip()
        if not re.match(r":?-{3,}:?", stripped_sep):
            table_errors.append(f"Table in '{note_title}' at body line {table_start_line_in_body + 2}, column {col_idx + 1}: Invalid separator format '{stripped_sep}'. Must be :---, ---:, or :---: (3+ hyphens).")
        
        if stripped_sep.startswith(':') and stripped_sep.endswith(':'):
            alignment_types.append('center')
        elif stripped_sep.endswith(':'):
            alignment_types.append('right')
        elif stripped_sep.startswith(':'):
            alignment_types.append('left')
        else:
            alignment_types.append('left') # Default to left if no explicit markers
        
        min_column_visual_widths[col_idx] = max(min_column_visual_widths[col_idx], len(stripped_sep))

    # 3. Validate data rows & update min_column_visual_widths
    for row_idx, line in enumerate(table_lines[2:]): # Start from the third line (after header and separator)
        line_num_in_body = table_start_line_in_body + 3 + row_idx
        stripped_line = line.strip()

        if not (stripped_line.startswith('|') and stripped_line.endswith('|')):
            table_errors.append(f"Table in '{note_title}' at body line {line_num_in_body}: Data row is missing outer pipes. Line: '{line}'.")
            continue

        cells_with_pipes = stripped_line.split('|')
        cells = [c.strip() for c in cells_with_pipes if c.strip()] # Filter empty strings from splits

        if len(cells) != num_columns:
            table_errors.append(f"Table in '{note_title}' at body line {line_num_in_body}: Mismatched number of cells ({len(cells)}) vs header columns ({num_columns}). Line: '{line}'.")
            continue

        for col_idx, cell_content in enumerate(cells):
            # Update min_column_visual_widths based on cell content
            min_column_visual_widths[col_idx] = max(min_column_visual_widths[col_idx], len(cell_content))

            # Check for emojis (prohibited)
            emoji_pattern = re.compile(r"[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F1E0-\U0001F1FF\U00002702-\U000027B0]")
            if emoji_pattern.search(cell_content):
                table_errors.append(f"Table in '{note_title}' at body line {line_num_in_body}, column {col_idx + 1}: Emojis are strictly prohibited in table cells. Content: '{cell_content}'.")

            # Multi-line cell rules:
            if len(cell_content) > 50 and "<br>" not in cell_content:
                table_errors.append(f"Table in '{note_title}' at body line {line_num_in_body}, column {col_idx + 1}: Cell content is long ({len(cell_content)} chars) but missing `<br>` for multi-line formatting. Content: '{cell_content[:50]}...'.")
    
    # 4. Consistent Column Widths (Alignment of pipes)
    # This check is complex to do purely on original lines with varying inner whitespace.
    # We rely on previous checks for pipe presence and consistent column count.
    # The "equal column widths" is more of a rendered visual aesthetic achieved by padding.

    # 5. Check for table title being inside table (prohibited)
    # This checks header cells specifically for any H-level markdown.
    for cell in headers:
        if re.match(r"^#+\s*", cell):
            table_errors.append(f"Table in '{note_title}' at body line {table_start_line_in_body + 1}: Table title found *inside* the table header, which is prohibited. Table titles must be above the table.")
            break

    # 6. Alignment Rules heuristic
    header_texts_lower = [h.lower() for h in headers]
    for col_idx, header_text in enumerate(header_texts_lower):
        actual_alignment = alignment_types[col_idx]
        
        if ("item" in header_text or "text" in header_text or "description" in header_text) and actual_alignment != "left":
            table_errors.append(f"Table in '{note_title}' at body line {table_start_line_in_body + 1}, column {col_idx + 1} ('{headers[col_idx]}'): Header implies left alignment but has '{actual_alignment}' marker in separator.")
        elif ("number" in header_text or "value" in header_text or "count" in header_text) and actual_alignment != "right":
            table_errors.append(f"Table in '{note_title}' at body line {table_start_line_in_body + 1}, column {col_idx + 1} ('{headers[col_idx]}'): Header implies right alignment but has '{actual_alignment}' marker in separator.")
        elif ("category" in header_text or "label" in header_text) and actual_alignment != "center":
            table_errors.append(f"Table in '{note_title}' at body line {table_start_line_in_body + 1}, column {col_idx + 1} ('{headers[col_idx]}'): Header implies center alignment but has '{actual_alignment}' marker in separator.")

    return table_errors


def _validate_boxed_formula_latex(latex_block_content: str, note_title: str, line_start_idx: int) -> List[str]:
    """
    Validates the specific rules for LaTeX boxed formulas within a $$...$$ block.
    Assumes `latex_block_content` includes the `$$` delimiters.
    """
    latex_errors: List[str] = []
    
    # Remove outer $$ for inner content processing
    inner_content = latex_block_content.strip()
    if not (inner_content.startswith('$$') and inner_content.endswith('$$')):
        latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}: '$$' markers are missing or malformed. Content: '{latex_block_content[:50].replace('\n', ' ')}...'.")
        return latex_errors # Cannot parse inner content reliably

    # Extract content between $$
    inner_content = inner_content[2:-2].strip()

    boxed_matches = list(re.finditer(r"\\boxed\{(.*?)\}", inner_content, re.DOTALL))

    # Check for simple numerical answers that should be plain text, unless part of a larger boxed/aligned structure
    if not boxed_matches and not re.search(r"\\begin\{aligned\}", inner_content):
        if re.fullmatch(r"[\d.,\s]+\s*\\?(?:[a-zA-Z]+)?", inner_content.strip()):
            latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}: Simple numerical answers must be plain text, NOT within a `$$...$$` block. Content: '{inner_content}'.")
        return latex_errors # If no boxes and not aligned, other checks are irrelevant here

    if len(boxed_matches) > 1:
        # Check for `\qquad` separation between multiple boxes
        if not re.search(r"\\boxed\{.*?\}\s*\\qquad\s*\\boxed\{.*?\}", inner_content, re.DOTALL):
            latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}: Multiple `\\boxed{{}}` environments must be separated by `\\qquad`. Found content between boxes that is not `\\qquad`.")
        else:
            # Check for similar structure with `\qquad`
            two_boxes_match = re.match(r"\\boxed\{(.*?)\}\s*\\qquad\s*\\boxed\{(.*?)\}", inner_content, re.DOTALL)
            if two_boxes_match:
                box1_content = two_boxes_match.group(1)
                box2_content = two_boxes_match.group(2)
                # Simple heuristic for "similar structure": count non-whitespace/alphanumeric characters
                ops1 = len(re.findall(r"[^a-zA-Z0-9\s]", box1_content))
                ops2 = len(re.findall(r"[^a-zA-Z0-9\s]", box2_content))
                if abs(ops1 - ops2) > 3: # Allow some deviation but flag large differences
                    latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}: Side-by-side boxed formulas with `\\qquad` appear to have dissimilar structure. Review '{box1_content[:20].replace('\n', ' ')}...' and '{box2_content[:20].replace('\n', ' ')}...'.")

    for match_idx, match in enumerate(boxed_matches):
        boxed_inner_content = match.group(1).strip()
        
        # `\displaystyle` Requirement: Presence of `\displaystyle` (unless `\textbf` for theorems)
        if r'\displaystyle' not in boxed_inner_content and r'\textbf' not in boxed_inner_content:
            latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}, box {match_idx + 1}: Missing `\\displaystyle` inside `\\boxed{{}}` (unless it's a theorem/definition box). Content: '{boxed_inner_content}'.")

        # Explanation Word Limits and Punctuation for `\quad \text{(Explanation)}`
        explanation_in_box_match = re.search(r"\\quad\\text\{\s*\(.+?\)\s*\}$", boxed_inner_content)
        if explanation_in_box_match: # This looks for text *inside* the boxed content with \quad\text
            explanation_text = explanation_in_box_match.group(1).strip()
            words = explanation_text.split()
            if len(words) > 5:
                latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}, box {match_idx + 1}: Explanation inside `\\text{{}}` within `\\boxed{{}}` should be max 5 words. Found '{explanation_text}' ({len(words)} words).")
            if re.search(r"[.?!]", explanation_text):
                latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}, box {match_idx + 1}: Explanation inside `\\text{{}}` within `\\boxed{{}}` must not be a full sentence (contains punctuation). Content: '{explanation_text}'.")
        
        # `\begin{aligned}` Placement: correctly wrapped *immediately inside* `\boxed{}` for final boxed derivations
        if r'\begin{aligned}' in boxed_inner_content and not boxed_inner_content.strip().startswith(r'\begin{aligned}'):
            latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}, box {match_idx + 1}: `\\begin{{aligned}}` found within `\\boxed{{}}` but not starting immediately after `\\boxed{{}}`. Should be `\\boxed{{\\begin{{aligned}}...`. Content: '{boxed_inner_content[:50].replace('\n', ' ')}...'.")

    # Check for excessive double boxing
    double_boxed_pattern = re.compile(r"\\fbox\{\\boxed\{\\displaystyle (.+?)\}\}", re.DOTALL)
    if len(list(double_boxed_pattern.finditer(inner_content))) > 1:
        latex_errors.append(f"LaTeX block in '{note_title}' at line {line_start_idx}: Only a maximum of one `\\fbox{{\\boxed{{}}}}` instance is permitted per note. Found multiple.")
    
    return latex_errors


def _validate_concept_questions_section(section_content: str, note_title: str, expected_heading_level: str, expected_concept_type: str, all_notes_metadata: List[Dict[str, Any]], section_start_line_in_body: int) -> List[str]:
    """
    Helper function to validate question blocks within a Foundational, Core, or Supporting section.
    """
    section_errors: List[str] = []

    # Pattern to find '### [[Concept]] Questions' or '##### [[Concept]] Questions'
    concept_questions_h_pattern = re.compile(rf"^{expected_heading_level}\s*\[\[([^\]]+?)\]\] Questions\s*$", re.MULTILINE)
    
    found_concept_blocks = False
    for h_match in concept_questions_h_pattern.finditer(section_content):
        found_concept_blocks = True
        concept_link = h_match.group(1).strip()
        
        # Check canonicalization of concept link
        if not vault_utils.get_canonical_title(concept_link) == concept_link:
            section_errors.append(f"Concept link '[[{concept_link}]]' in '{expected_heading_level} Questions' heading is not canonical. Expected: '[[{vault_utils.get_canonical_title(concept_link)}]]'.")
        
        # Check if the linked concept exists and is of the expected type
        concept_exists = any(vault_utils.get_canonical_title(m.get("title")) == vault_utils.get_canonical_title(concept_link) and m.get("type") == expected_concept_type for m in all_notes_metadata if m.get("title"))
        if not concept_exists:
            section_errors.append(f"Concept '[[{concept_link}]]' in '{expected_heading_level} Questions' heading links to a non-existent or non-{expected_concept_type} type note.")
        
        # Extract the content of this concept's question block
        # This regex captures everything after the heading until the next heading of same/higher level, or '---', or end of section
        q_block_start_idx = h_match.end()
        # Adjusted regex to handle either a higher level heading (like '##' or '####')
        # or a '---' or end of section.
        next_heading_or_sep_match = re.search(rf"^\s*(?:#{{1,{len(expected_heading_level)}}}|#{{1,{len(expected_heading_level) - 1}}}|\n---)", section_content[q_block_start_idx:], re.MULTILINE)
        
        if next_heading_or_sep_match:
            questions_text = section_content[q_block_start_idx : q_block_start_idx + next_heading_or_sep_match.start()]
        else:
            questions_text = section_content[q_block_start_idx:]
        
        section_errors.extend(_validate_individual_question_block(
            concept_link=concept_link,
            questions_text=questions_text,
            note_title=note_title,
            all_notes_metadata=all_notes_metadata,
            section_start_line_in_body=section_start_line_in_body + section_content[:h_match.start()].count('\n') + 1 # Adjust for concept heading offset
        ))
    
    if not found_concept_blocks:
        section_errors.append(f"Section for '{expected_concept_type} Concepts' is missing any '{expected_heading_level} [[Concept]] Questions' sub-sections.")

    return section_errors


def _validate_individual_question_block(concept_link: str, questions_text: str, note_title: str, all_notes_metadata: List[Dict[str, Any]], section_start_line_in_body: int) -> List[str]:
    """Helper to validate a single block of questions for one concept (main questions + sub-questions)."""
    block_errors = []
    
    # Split into individual main questions using #. as delimiter
    # This pattern needs to be careful not to split sub-questions.
    # It looks for '#. Type: [[...]]' followed by content until the next '#. Type:' or end of string.
    main_question_blocks = re.finditer(r"(^\s*#\.\s*Type:\s*\[\[([^\]]+?)\]\]\s*(.+?)(?=\n\s*#\.|\n---|\Z))", questions_text, re.DOTALL | re.MULTILINE)
    
    current_q_num = 1
    found_main_questions = False
    
    for q_match in main_question_blocks:
        found_main_questions = True
        full_q_block_raw = q_match.group(0) # The entire matched question block
        
        # Extract the type tag link from the matched block
        type_tag_link_match = re.search(r"Type:\s*\[\[([^\]]+?)\]\]", full_q_block_raw)
        type_tag_link = type_tag_link_match.group(1).strip() if type_tag_link_match else "N/A_Link"
        
        # Validate "Type: [[Canonical_Concept_Title]]" tag
        if not type_tag_link == concept_link:
            block_errors.append(f"Main question tag 'Type: [[{type_tag_link}]]' does not match block's concept '[[{concept_link}]]' (Main Q {current_q_num}).")
        
        # Check numbering (the #. part)
        full_q_block_lines = full_q_block_raw.splitlines()
        # Corrected: check only the first line of the question block
        if full_q_block_lines and not full_q_block_lines[0].strip().startswith(f"{current_q_num}. Type: [[{type_tag_link}]]"):
             block_errors.append(f"Main question for '[[{concept_link}]]' at question number {current_q_num} is not correctly numbered or formatted. Expected '{current_q_num}. Type: [[...]]'. Found: '{full_q_block_lines[0].strip() if full_q_block_lines else 'Empty'}'.")

        # Validate sub-questions (a), (b), (c)
        sub_questions_matches = re.finditer(r"^\s*\((\w)\)\s*(.*?)(?=\n\s*\(\w\)|\n\s*#\.|\n---|\Z)", full_q_block_raw, re.DOTALL | re.MULTILINE)
        
        current_sub_q_letter_code = ord('a')
        found_sub_questions = False
        for sub_q_match in sub_questions_matches:
            found_sub_questions = True
            letter = sub_q_match.group(1)
            sub_q_content = sub_q_match.group(2).strip()

            if letter != chr(current_sub_q_letter_code):
                block_errors.append(f"Sub-question for '[[{concept_link}]]' (Main Q {current_q_num}) out of order. Expected '({chr(current_sub_q_letter_code)})', Found '({letter})'.")
            
            if not sub_q_content:
                block_errors.append(f"Sub-question '({letter})' for '[[{concept_link}]]' (Main Q {current_q_num}) is empty.")

            current_sub_q_letter_code += 1
        
        if not found_sub_questions:
            block_errors.append(f"Main question {current_q_num} for '[[{concept_link}]]' has no sub-questions (a), (b), etc.")

        current_q_num += 1
    
    if not found_main_questions:
        block_errors.append(f"Concept '[[{concept_link}]]' section contains no main questions formatted with '#. Type: [[...]]'.")

    return block_errors


# ===========================
# ORCHESTRATOR VALIDATION FUNCTIONS
# ===========================

def validate_yaml_frontmatter(meta: Dict[str, Any], raw_note_content: str, note_title_for_log: str, note_type_for_log: str, all_notes_metadata: List[Dict[str, Any]]) -> List[str]:
    """
    Validates the YAML frontmatter of a single note.
    Returns a list of errors.
    """
    errors: List[str] = []

    # Check for required universal fields
    required_fields = ["title", "created_at", "last_modified", "deployment_batch_id", "uid",
                       "type", "course", "year", "semester", "credits", "original_source", "aliases"]
    for field in required_fields:
        if field not in meta:
            errors.append(f"Missing required field '{field}'.")
    
    # Validate specific field types and formats
    if "title" in meta:
        title = meta["title"]
        if not isinstance(title, str) or not vault_utils.get_canonical_title(title) == title:
            errors.append(f"'title' field '{title}' is not a canonical, underscore-separated, Title_Case string. Expected: '{vault_utils.get_canonical_title(title)}'.")
        if re.search(r"[\(\)]", title):
            errors.append(f"'title' field '{title}' contains prohibited parentheses '()'.")

    if "type" in meta and meta["type"] not in EXPECTED_H1_SECTIONS:
        errors.append(f"'type' field '{meta['type']}' is not a recognized type.")
    
    # Validate canonicalization of year, semester, course
    for field in ["year", "semester", "course"]:
        if field in meta:
            value = meta[field]
            if not isinstance(value, str) or not vault_utils.get_canonical_title(value) == value:
                errors.append(f"'{field}' field '{value}' is not canonical. Expected: '{vault_utils.get_canonical_title(value)}'.")
            if re.search(r"[\(\)]", value):
                errors.append(f"'{field}' field '{value}' contains prohibited parentheses '()'.")


    if "credits" in meta and not isinstance(meta["credits"], int):
        errors.append(f"'credits' field '{meta['credits']}' is not an integer.")

    if "aliases" in meta:
        if not isinstance(meta["aliases"], list):
            errors.append(f"'aliases' field is not a list.")
        else:
            for alias in meta["aliases"]:
                if not isinstance(alias, str) or not vault_utils.get_canonical_title(alias) == alias:
                    errors.append(f"Alias '{alias}' is not a canonical, underscore-separated, Title_Case string. Expected: '{vault_utils.get_canonical_title(alias)}'.")
                if re.search(r"[\(\)]", alias):
                    errors.append(f"Alias '{alias}' contains prohibited parentheses '()'.")

    # Type-specific field checks
    if note_type_for_log == "Unit":
        if "unit" in meta:
            errors.append(f"(type: Unit) has an unexpected 'unit' field. Unit notes should not have a unit field.")
        if "parent" in meta:
            errors.append(f"(type: Unit) has an unexpected 'parent' field. Unit notes should not have a parent.")
        if not note_title_for_log.endswith("_Hub"):
             errors.append(f"(type: Unit) title does not end with '_Hub'.")
    
    elif note_type_for_log == "Foundational":
        if "unit" not in meta:
            errors.append(f"(type: Foundational) is missing required 'unit' field.")
        else:
            unit_title = meta["unit"]
            if not isinstance(unit_title, str) or not vault_utils.get_canonical_title(unit_title) == unit_title:
                errors.append(f"(type: Foundational) 'unit' field '{unit_title}' is not canonical. Expected: '{vault_utils.get_canonical_title(unit_title)}'.")
            if re.search(r"[\(\)]", unit_title):
                errors.append(f"(type: Foundational) 'unit' field '{unit_title}' contains prohibited parentheses '()'.")
            if not any(vault_utils.get_canonical_title(n.get('title')) == vault_utils.get_canonical_title(unit_title) and n.get('type') == 'Unit' for n in all_notes_metadata):
                errors.append(f"(type: Foundational) 'unit' field '{unit_title}' refers to a non-existent or non-Unit type note.")
        if "parent" in meta:
            errors.append(f"(type: Foundational) has an unexpected 'parent' field. Foundational notes should not have a parent.")
        
    elif note_type_for_log == "Core":
        if "unit" not in meta:
            errors.append(f"(type: Core) is missing required 'unit' field.")
        else:
            unit_title = meta["unit"]
            if not isinstance(unit_title, str) or not vault_utils.get_canonical_title(unit_title) == unit_title:
                errors.append(f"(type: Core) 'unit' field '{unit_title}' is not canonical. Expected: '{vault_utils.get_canonical_title(unit_title)}'.")
            if re.search(r"[\(\)]", unit_title):
                errors.append(f"(type: Core) 'unit' field '{unit_title}' contains prohibited parentheses '()'.")
            if not any(vault_utils.get_canonical_title(n.get('title')) == vault_utils.get_canonical_title(unit_title) and n.get('type') == 'Unit' for n in all_notes_metadata):
                errors.append(f"(type: Core) 'unit' field '{unit_title}' refers to a non-existent or non-Unit type note.")
        
        if "parent" not in meta:
            errors.append(f"(type: Core) is missing required 'parent' field.")
        else:
            parent_title = meta["parent"]
            if not isinstance(parent_title, str) or not vault_utils.get_canonical_title(parent_title) == parent_title:
                errors.append(f"(type: Core) 'parent' field '{parent_title}' is not canonical. Expected: '{vault_utils.get_canonical_title(parent_title)}'.")
            if re.search(r"[\(\)]", parent_title):
                errors.append(f"(type: Core) 'parent' field '{parent_title}' contains prohibited parentheses '()'.")
            if not any(vault_utils.get_canonical_title(n.get('title')) == vault_utils.get_canonical_title(parent_title) and n.get("type") == "Foundational" for n in all_notes_metadata):
                errors.append(f"(type: Core) 'parent' field '{parent_title}' refers to a non-existent or non-Foundational type note.")
    
    elif note_type_for_log == "Supporting":
        if "unit" not in meta:
            errors.append(f"(type: Supporting) is missing required 'unit' field.")
        else:
            unit_title = meta["unit"]
            if not isinstance(unit_title, str) or not vault_utils.get_canonical_title(unit_title) == unit_title:
                errors.append(f"(type: Supporting) 'unit' field '{unit_title}' is not canonical. Expected: '{vault_utils.get_canonical_title(unit_title)}'.")
            if re.search(r"[\(\)]", unit_title):
                errors.append(f"(type: Supporting) 'unit' field '{unit_title}' contains prohibited parentheses '()'.")
            if not any(vault_utils.get_canonical_title(n.get('title')) == vault_utils.get_canonical_title(unit_title) and n.get('type') == 'Unit' for n in all_notes_metadata):
                errors.append(f"(type: Supporting) 'unit' field '{unit_title}' refers to a non-existent or non-Unit type note.")
        
        if "parent" not in meta:
            errors.append(f"(type: Supporting) is missing required 'parent' field.")
        else:
            parent_title = meta["parent"]
            if not isinstance(parent_title, str) or not vault_utils.get_canonical_title(parent_title) == parent_title:
                errors.append(f"(type: Supporting) 'parent' field '{parent_title}' is not canonical. Expected: '{vault_utils.get_canonical_title(parent_title)}'.")
            if re.search(r"[\(\)]", parent_title):
                errors.append(f"(type: Supporting) 'parent' field '{parent_title}' contains prohibited parentheses '()'.")
            if not any(vault_utils.get_canonical_title(n.get('title')) == vault_utils.get_canonical_title(parent_title) and n.get('type') == 'Core' for n in all_notes_metadata):
                errors.append(f"(type: Supporting) 'parent' field '{parent_title}' refers to a non-existent or non-Core type note.")
    
    elif note_type_for_log == "Questions":
        # Check title format for Questions note
        course_name = meta.get('course', 'Unsorted_Course')
        # This part will be validated more precisely in validate_questions_note
        if not note_title_for_log.endswith("_Possible_Questions"):
             errors.append(f"(type: Questions) title does not end with '_Possible_Questions'.")
        
        if "unit" in meta:
            errors.append(f"(type: Questions) has an unexpected 'unit' field. Questions notes should not have a unit field.")
        if "parent" in meta:
            errors.append(f"(type: Questions) has an unexpected 'parent' field. Questions notes should not have a parent.")

    # Check for placeholder UIDs/deployment batch IDs (indicating new note that hasn't been deployed yet)
    # These are warnings, not errors, as deployer fixes them.
    if meta.get("uid") == "placeholder_uid_1234567890abcdef":
        errors.append(f"Warning: 'uid' field is a placeholder. (Deployer will fix)")
    if meta.get("deployment_batch_id") == "AI_GENERATED_BATCH":
        errors.append(f"Warning: 'deployment_batch_id' field is a placeholder. (Deployer will fix)")
    
    # Check `created_at` and `last_modified` if they are placeholders from the template
    if meta.get("created_at") == "YYYY-MM-DDTHH:MM:SSZ":
        errors.append(f"Warning: 'created_at' field is a placeholder. (Deployer will fix)")
    if meta.get("last_modified") == "YYYY-MM-DDTHH:MM:SSZ":
        errors.append(f"Warning: 'last_modified' field is a placeholder. (Deployer will fix)")

    # Check for YAML field order
    expected_yaml_order_keys = [
        "title", "created_at", "last_modified", "deployment_batch_id", "uid",
        "type", "course", "year", "semester", "credits", "original_source", "aliases",
    ]
    
    # Add conditional fields based on type, maintaining strict order
    if note_type_for_log in ["Foundational", "Core", "Supporting"]:
        expected_yaml_order_keys.append("unit")
    if note_type_for_log in ["Core", "Supporting"]:
        expected_yaml_order_keys.append("parent")
    
    expected_yaml_order_keys.extend(["ai_refinement_log", "math"]) # Optional fields, but still ordered if present

    actual_present_keys = [k for k in meta if k in expected_yaml_order_keys] # Only check keys that are present in both
    
    # Create a mapping of key to its expected position
    key_to_expected_idx = {key: idx for idx, key in enumerate(expected_yaml_order_keys)}

    for i in range(len(actual_present_keys)):
        current_key = actual_present_keys[i]
        
        # Check if the current key is in our expected order list. If not, it's an unexpected key,
        # but the purpose of this check is specifically for *order* of *expected* keys.
        if current_key not in key_to_expected_idx:
            continue # This key is not in our strict order list, ignore for order check.

        # Find the first key in expected_yaml_order_keys that is *after* the previous key in actual_present_keys
        # and matches the current key.
        # This is a simpler way to check relative order.
        # Check if the current key appears earlier in the actual list than it should relative to the next keys
        if i > 0:
            prev_key = actual_present_keys[i-1]
            if prev_key in key_to_expected_idx and key_to_expected_idx[current_key] < key_to_expected_idx[prev_key]:
                errors.append(f"Field '{current_key}' is out of order. It should appear after '{prev_key}'.")


    return errors

def validate_markdown_body_structure(body_content: str, meta: Dict[str, Any]) -> List[str]:
    """
    Validates the Markdown body structure, including H1 headings, blank lines, and separators.
    Returns a list of errors.
    """
    errors: List[str] = []
    note_type = meta.get("type", "Unknown")
    note_title = meta.get("title", "Untitled_Note")

    all_body_lines = body_content.splitlines()
    
    # --- CRITICAL FIX START: Check for exactly one blank line after YAML ---
    
    if not all_body_lines: # Completely empty body_content (no blank line, no content)
        if note_type not in ["MOC", "Questions"]: 
            errors.append(f"Content: Note has a completely empty Markdown body after YAML.")
        return errors

    start_line_offset = 0 
    
    # Count initial blank lines
    initial_blank_lines = 0
    while start_line_offset < len(all_body_lines) and all_body_lines[start_line_offset].strip() == "":
        initial_blank_lines += 1
        start_line_offset += 1
    
    if initial_blank_lines == 0:
        errors.append(f"Formatting: Missing exactly one blank line immediately after the closing YAML '---'. (First content at Line {start_line_offset + 1} in body).")
    elif initial_blank_lines > 1:
        errors.append(f"Formatting: More than one blank line ({initial_blank_lines}) immediately after the closing YAML '---'. Expected exactly one blank line. (First content at Line {start_line_offset + 1} in body).")
    
    processed_lines_for_h1_check = all_body_lines[start_line_offset:] # This is the content *after* the initial blank lines
    
    if not processed_lines_for_h1_check: 
        if note_type not in ["MOC", "Questions"]:
            errors.append(f"Content: Note has an empty Markdown body after YAML and leading blank lines.")
        return errors
    # --- CRITICAL FIX END ---

    # 2. Validate H1 Headings and their order
    expected_h1s = EXPECTED_H1_SECTIONS.get(note_type, [])

    # Explicitly re-initialize to avoid any theoretical UnboundLocalError issues, even if redundant
    actual_headings_in_content: List[Tuple[str, int, int]] = [] 
    
    # Iterate through the content to extract all headings and their relative positions.
    temp_line_idx_in_body = start_line_offset 
    for line_content in all_body_lines[start_line_offset:]:
        stripped_line = line_content.strip()
        h_match = re.match(r"^(#+)\s+(.*)", stripped_line)
        if h_match:
            actual_headings_in_content.append((h_match.group(2).strip(), len(h_match.group(1)), temp_line_idx_in_body))
        temp_line_idx_in_body += 1

    # Special case for Questions note's primary H1: check its full pattern
    if note_type == "Questions":
        first_h1_text_found = ""
        first_h1_overall_line_num = -1 

        if actual_headings_in_content: 
            if actual_headings_in_content[0][1] == 1: # [0][1] is heading level
                first_h1_text_found = actual_headings_in_content[0][0] # [0][0] is heading text
                first_h1_overall_line_num = actual_headings_in_content[0][2] + 1 # [0][2] is 0-indexed offset in body, +1 for 1-indexed file line

        # Only proceed with pattern matching if a first H1 was actually found and extracted
        if first_h1_overall_line_num != -1: 
            unit_hub_h1_pattern = re.compile(r"^\[\[([^\]]+?)\]\] Questions\s*$", re.MULTILINE)
            if not unit_hub_h1_pattern.match(first_h1_text_found):
                errors.append(f"Structure: Primary H1 heading for Questions note is not in the required format '# [[Unit_Hub_Title]] Questions'. Found: '# {first_h1_text_found}' at line {first_h1_overall_line_num}.")
        else: # If no valid first H1, then this specific error is about its absence/malformation
            errors.append(f"Structure: Primary H1 heading for Questions note could not be identified or extracted correctly. This might be due to missing H1 or internal parsing issues.")
        
        # After handling the primary H1, the remaining expected H1s are checked as usual, starting from the next index.
        # We need to adjust expected_h1s and current_processed_content_idx for this.
        # The 'Questions' entry in expected_h1s is a placeholder for the special H1.
        if "Questions" in expected_h1s:
            expected_h1s_for_order_check = expected_h1s[expected_h1s.index("Questions") + 1:]
        else:
            expected_h1s_for_order_check = expected_h1s

        # Adjust current_processed_content_idx to start after the first H1 if it was successfully found
        if actual_headings_in_content and actual_headings_in_content[0][1] == 1:
            current_processed_content_idx = 1
        else:
            current_processed_content_idx = 0 # If first H1 wasn't found/valid, start checking from beginning
        
    else: # For non-Questions notes, process all expected H1s from the beginning
        expected_h1s_for_order_check = expected_h1s
        current_processed_content_idx = 0


    # Now, validate H1 presence and order for remaining (or all non-Questions) H1s
    for expected_h1_text in expected_h1s_for_order_check:
        found_expected_h1_in_sequence = False
        for i in range(current_processed_content_idx, len(actual_headings_in_content)):
            h_text, h_level, line_num = actual_headings_in_content[i]
            if h_level == 1 and h_text == expected_h1_text:
                found_expected_h1_in_sequence = True
                current_processed_content_idx = i + 1 
                break
        if not found_expected_h1_in_sequence:
            errors.append(f"Structure: Missing expected H1 heading: '# {expected_h1_text}' or it's out of order.")
    
    # Check for unexpected H1s (only for non-MOC, non-Questions types)
    if note_type not in ["MOC", "Questions"]: 
        for i, (h_text, h_level, line_num) in enumerate(actual_headings_in_content):
            if h_level == 1 and h_text not in expected_h1s: # Check against original expected_h1s here
                errors.append(f"Structure: Unexpected H1 heading: '# {h_text}' at line {line_num + 1}. Only predefined H1 headings are allowed.")

    # Special check for atomic notes: no H1s between Detailed Explanation and Why It's Important
    if note_type in ["Foundational", "Core", "Supporting"]:
        detailed_exp_idx = -1
        why_important_idx = -1
        
        for i, (h_text, h_level, line_num) in enumerate(actual_headings_in_content):
            if h_level == 1 and h_text == "Detailed Explanation":
                detailed_exp_idx = i
            elif h_level == 1 and h_text == "Why It's Important & Where You'll See It":
                why_important_idx = i
        
        if detailed_exp_idx != -1 and why_important_idx != -1 and detailed_exp_idx < why_important_idx:
            for i in range(detailed_exp_idx + 1, why_important_idx):
                h_text, h_level, line_num = actual_headings_in_content[i]
                if h_level == 1:
                    errors.append(f"Structure: Unexpected H1 heading '# {h_text}' at line {line_num + 1} found between 'Detailed Explanation' and 'Why It's Important & Where You'll See It'.")


    # 3. Blank Lines Around H1s, Separators, and Trailing Separators
    prev_line_was_h1 = False
    prev_line_was_blank = False
    prev_line_was_separator = False
    
    current_line_idx_in_body = start_line_offset 
    
    for i, line in enumerate(all_body_lines[start_line_offset:]):
        stripped_line = line.strip()
        
        is_h1 = re.match(r"^(#)\s+(.*)", stripped_line)
        is_separator = stripped_line == "---"
        is_blank = stripped_line == ""

        # Check blank line before H1
        if is_h1:
            if i > 0 and not prev_line_was_blank and not prev_line_was_separator and not prev_line_was_h1:
                errors.append(f"Formatting: H1 heading '# {is_h1.group(2)}' at line {current_line_idx_in_body + 1} is not preceded by exactly one blank line.")
            elif i > 0 and prev_line_was_blank and (current_line_idx_in_body -1 >= 0 and all_body_lines[current_line_idx_in_body - 1].strip() == ""): # Check for >1 blank lines
                errors.append(f"Formatting: H1 heading '# {is_h1.group(2)}' at line {current_line_idx_in_body + 1} is preceded by more than one blank line.")
            elif i == 0 and prev_line_was_blank: 
                pass 
        
        # Check blank line after H1
        if prev_line_was_h1:
            if not is_blank:
                errors.append(f"Formatting: H1 heading '# {all_body_lines[current_line_idx_in_body - 1 - start_line_offset].strip()[2:]}' at line {current_line_idx_in_body} is not followed by exactly one blank line.")
            elif is_blank and (current_line_idx_in_body + 1 < len(all_body_lines)) and all_body_lines[current_line_idx_in_body + 1].strip() == "":
                 errors.append(f"Formatting: H1 heading '# {all_body_lines[current_line_idx_in_body - 1 - start_line_offset].strip()[2:]}' at line {current_line_idx_in_body} is followed by more than one blank line.")

        # Check blank line around separator `---`
        if is_separator:
            if i > 0 and not prev_line_was_blank:
                errors.append(f"Formatting: Separator '---' at line {current_line_idx_in_body + 1} is not preceded by exactly one blank line.")
            if (current_line_idx_in_body + 1 < len(all_body_lines)) and all_body_lines[current_line_idx_in_body + 1].strip() != "":
                errors.append(f"Formatting: Separator '---' at line {current_line_idx_in_body + 1} is not followed by a blank line.")
            elif (current_line_idx_in_body + 1 < len(all_body_lines)) and (current_line_idx_in_body + 2 < len(all_body_lines)) and all_body_lines[current_line_idx_in_body + 1].strip() == "" and all_body_lines[current_line_idx_in_body + 2].strip() == "":
                 errors.append(f"Formatting: Separator '---' at line {current_line_idx_in_body + 1} is followed by more than one blank line.")

        prev_line_was_h1 = bool(is_h1)
        prev_line_was_blank = is_blank
        prev_line_was_separator = is_separator
        current_line_idx_in_body += 1

    # Final check for trailing '---' (or its absence for Questions notes)
    if note_type == "Questions":
        if all_body_lines and all_body_lines[-1].strip() == "---":
            errors.append(f"Formatting: Note (type: Questions) has an unexpected trailing '---' separator.")
    else:
        last_non_blank_line_idx = -1
        for i in range(len(all_body_lines) -1, -1, -1):
            if all_body_lines[i].strip():
                last_non_blank_line_idx = i
                break
        
        if last_non_blank_line_idx == -1 or all_body_lines[last_non_blank_line_idx].strip() != "---":
            errors.append(f"Formatting: Note (type: {note_type}) is missing the mandatory trailing '---' separator.")
        elif last_non_blank_line_idx < len(all_body_lines) - 1:
            errors.append(f"Formatting: Note (type: {note_type}) has extra blank lines or content after the trailing '---' separator.")
        
    return errors


def validate_wiki_links(body_content: str, all_notes_metadata: List[Dict[str, Any]], note_title_for_log: str) -> List[str]:
    """
    Validates internal wiki-links in the note's content.
    Returns a list of errors.
    """
    errors: List[str] = []
    
    canonical_title_to_meta = {vault_utils.get_canonical_title(meta.get("title")): meta for meta in all_notes_metadata if meta.get("title")}

    wiki_link_pattern = re.compile(r"\[\[([^\]]+?)\]\]")
    for match in wiki_link_pattern.finditer(body_content):
        link_target = match.group(1).strip()
        
        canonical_link_target = vault_utils.get_canonical_title(link_target)
        
        if not canonical_link_target == link_target:
            errors.append(f"Link to '[[{link_target}]]' is not canonical. Expected: '[[{canonical_link_target}]]'.")
        
        # Check for prohibited display text in wiki-links (e.g., [[Link | Display Text]])
        if '|' in link_target: # This check needs to run BEFORE vault_utils.process_code_blocks strips it,
                               # or on the *original* content if we want to report it as the AI's deviation.
                               # For now, it runs on the processed_body_content_for_links which is after
                               # vault_utils has converted [[Link | Display Text]] to [[Link]]
            errors.append(f"Wiki-Link Error: Link '[[{link_target}]]' contains prohibited display text. Display text is not allowed in wiki-links.")


        target_meta = canonical_title_to_meta.get(canonical_link_target)
        
        if not target_meta:
            errors.append(f"Link to missing note '[[{link_target}]]'.")
        else:
            target_note_type = target_meta.get('type')
            if target_note_type not in ["Unit", "Foundational", "Core", "Supporting", "MOC", "Questions"]:
                errors.append(f"Link to '[[{link_target}]]' which is of unsupported type '{target_note_type}'.")

    return errors


def validate_code_latex_blocks(body_content: str, meta: Dict[str, Any]) -> List[str]:
    """
    Validates code blocks (custom markers) and LaTeX blocks (direct $$...$$).
    Includes new check for Obsidian callouts.
    Returns a list of errors.
    """
    errors: List[str] = []
    note_title = meta.get("title", "Untitled_Note")
    note_type = meta.get("type", "Unknown")

    in_code_block = False
    current_code_language = None
    latex_block_start_line = -1
    latex_block_buffer = []

    lines = body_content.splitlines()
    for i, line in enumerate(lines):
        line_num_in_body = i 

        start_code_match = re.match(r"^\s*--- START_CODE:(\w+) ---\s*$", line)
        end_code_match = re.match(r"^\s*--- END_CODE:(\w+) ---\s*$", line)
        
        # New: Check for Obsidian callouts (STRICTLY PROHIBITED)
        if re.match(r"^\s*>\s*\[!\w+\]", line):
            errors.append(f"Formatting: Prohibited Obsidian callout found at line {line_num_in_body + 1}. Callouts are not allowed.")

        if start_code_match:
            language = start_code_match.group(1)
            if language not in ["python", "java", "cpp", "sql", "json", "text", "mermaid"]:
                errors.append(f"Code Block: Unsupported code block language '{language}' at line {line_num_in_body + 1}. Must be one of python, java, cpp, sql, json, text, mermaid.")
            if in_code_block:
                errors.append(f"Code Block: Nested or unclosed code block detected (started '{current_code_language}', now starting '{language}') at line {line_num_in_body + 1}.")
            in_code_block = True
            current_code_language = language
            if i > 0 and lines[i-1].strip() != "":
                errors.append(f"Code Block Formatting: `--- START_CODE:{language} ---` at line {line_num_in_body + 1} is not preceded by a blank line.")
            if i + 1 < len(lines) and lines[i+1].strip() == "":
                 errors.append(f"Code Block Formatting: `--- START_CODE:{language} ---` at line {line_num_in_body + 1} is followed by an extra blank line. Should be direct content.")


        elif end_code_match:
            language = end_code_match.group(1)
            if not in_code_block or language != current_code_language:
                errors.append(f"Code Block: Mismatched or unexpected `--- END_CODE:{language} ---` tag at line {line_num_in_body + 1}.")
            in_code_block = False
            current_code_language = None
            if i > 0 and lines[i-1].strip() == "": 
                errors.append(f"Code Block Formatting: `--- END_CODE:{language} ---` at line {line_num_in_body + 1} is preceded by an extra blank line. Should be direct content.")
            if i + 1 < len(lines) and lines[i+1].strip() != "":
                errors.append(f"Code Block Formatting: `--- END_CODE:{language} ---` at line {line_num_in_body + 1} is not followed by a blank line.")
        
        if not in_code_block and re.match(r"^\s*```", line.strip()):
            errors.append(f"Code Block: Prohibited Markdown triple backticks (```) found outside of custom code blocks at line {line_num_in_body + 1}. Use `--- START_CODE:lang ---` instead.")


        if not in_code_block: 
            if line.strip().startswith('$$'):
                if latex_block_start_line == -1: 
                    latex_block_start_line = line_num_in_body
                    latex_block_buffer = [line]
                else: 
                    latex_block_buffer.append(line)
                    latex_block_content = "\n".join(latex_block_buffer)
                    errors.extend(_validate_boxed_formula_latex(latex_block_content, note_title, latex_block_start_line + 1))
                    
                    if latex_block_start_line > 0 and lines[latex_block_start_line - 1].strip() != "":
                        errors.append(f"LaTeX Formatting: Display math block (first '$$') at line {latex_block_start_line + 1} is not preceded by a blank line.")
                    if line_num_in_body + 1 < len(lines) and lines[line_num_in_body + 1].strip() != "":
                        errors.append(f"LaTeX Formatting: Display math block (last '$$') at line {line_num_in_body + 1} is not followed by a blank line.")

                    latex_block_start_line = -1
                    latex_block_buffer = []
            elif latex_block_start_line != -1: 
                latex_block_buffer.append(line)
            
            if re.search(r"\$[^$]+\$", line) and re.search(r"`[^`]+`", line):
                if re.search(r"`.*?(\\sum|\\int|\\frac|\\sqrt|\\alpha|\\beta|\\gamma).*?`", line):
                    errors.append(f"LaTeX Formatting: Backticks (`` ` ``) are used for mathematical expressions at line {line_num_in_body + 1}, which is prohibited. Use `$` for inline math.")


    if in_code_block:
        errors.append(f"Code Block: Unclosed code block started with `--- START_CODE:{current_code_language} ---`.")

    if latex_block_start_line != -1:
        errors.append(f"LaTeX Block: Unclosed display math block started with '$$' at line {latex_block_start_line + 1}.")

    if note_type == "Theoretical":
        programming_languages = ["python", "java", "cpp", "sql"]
        for lang in programming_languages:
            if f"--- START_CODE:{lang} ---" in body_content:
                errors.append(f"Content: Note (type: {note_type}) contains programming code block (`--- START_CODE:{lang} ---`). Programming code is strictly prohibited in theoretical notes unless directly illustrating a computational algorithm related to a mathematical concept.")

    return errors


def validate_markdown_tables(body_content: str, note_title: str) -> List[str]:
    """
    Validates Markdown tables based on structural, alignment, and content rules.
    Returns a list of errors.
    """
    errors: List[str] = []
    lines = body_content.splitlines()
    in_table = False
    table_buffer: List[str] = []
    table_start_line_in_body = -1 

    for i, line in enumerate(lines):
        is_potential_table_line = '|' in line and (line.strip().startswith('|') or line.strip().endswith('|'))

        if is_potential_table_line and not in_table:
            # Check if the next line is a separator to confirm it's a table start
            if i + 1 < len(lines) and re.match(r"^\s*\|(?:[-:]+\|)+\s*$", lines[i+1]):
                in_table = True
                table_start_line_in_body = i
                table_buffer.append(line)
                continue
        
        if in_table:
            table_buffer.append(line)
            # Check for end of table: next line is not a table line OR it's the end of the content
            # Also ensure a blank line follows the table (or it's the end of file)
            is_end_of_content = (i + 1 == len(lines))
            next_line_is_blank = (i + 1 < len(lines) and lines[i+1].strip() == "")
            next_line_is_not_table_content = (i + 1 < len(lines) and not ('|' in lines[i+1] and (lines[i+1].strip().startswith('|') or lines[i+1].strip().endswith('|'))))

            # A table ends if:
            # 1. It's the end of the content.
            # 2. The next line is blank AND not part of a table (ensures a blank line after the table).
            # 3. The next line is not a blank line AND not part of a table (implies immediate end, which also requires a blank line).
            if is_end_of_content or (next_line_is_not_table_content and next_line_is_blank) or (next_line_is_not_table_content and not next_line_is_blank):
                errors.extend(_validate_single_markdown_table(table_buffer, note_title, table_start_line_in_body))
                
                # Check blank line BEFORE table
                if table_start_line_in_body > 0 and lines[table_start_line_in_body - 1].strip() != "":
                    errors.append(f"Table Formatting: Table at line {table_start_line_in_body + 1} is not preceded by a blank line.")
                
                # Check blank line AFTER table
                if not is_end_of_content and not next_line_is_blank:
                    errors.append(f"Table Formatting: Table at line {i + 1} is not followed by a blank line.")
                elif not is_end_of_content and next_line_is_blank and (i + 2 < len(lines) and lines[i+2].strip() == ""):
                    errors.append(f"Table Formatting: Table at line {i + 1} is followed by more than one blank line.")
                
                in_table = False
                table_buffer = []
                table_start_line_in_body = -1
        
    if in_table:
        errors.extend(_validate_single_markdown_table(table_buffer, note_title, table_start_line_in_body))
        errors.append(f"Table: Unclosed table block detected starting at line {table_start_line_in_body + 1}.")

    return errors


def validate_knowledge_graph_connections(body_content: str, meta: Dict[str, Any], all_notes_metadata: List[Dict[str, Any]]) -> List[str]:
    """
    Validates the # Knowledge Graph Connections section of an atomic note.
    Returns a list of errors.
    """
    errors: List[str] = []
    note_type = meta.get("type", "Unknown")
    note_title = meta.get("title", "Untitled_Note")
    
    if note_type not in ["Foundational", "Core", "Supporting"]:
        return errors 

    kgc_start_pattern = re.compile(r"^# Knowledge Graph Connections\s*$", re.MULTILINE)
    kgc_match = kgc_start_pattern.search(body_content)

    if not kgc_match:
        errors.append(f"Structure: Missing the mandatory '# Knowledge Graph Connections' section.")
        return errors

    kgc_section_content = body_content[kgc_match.end():]
    
    meta_unit_canonical = vault_utils.get_canonical_title(meta.get('unit', ''))
    meta_parent_canonical = vault_utils.get_canonical_title(meta.get('parent', ''))

    def _validate_kgc_link(link_line: str, expected_link_canonical: str, expected_type: str, relation_label: str, line_num: int):
        link_match = re.search(r"\[\[([^\]]+?)\]\]", link_line)
        if not link_match:
            errors.append(f"KGC Link: Expected a link for '{relation_label}' but none found in line: '{link_line}' at line {line_num + 1}.")
            return
        
        link_target = link_match.group(1).strip()
        canonical_link_target = vault_utils.get_canonical_title(link_target)

        if not canonical_link_target == link_target:
            errors.append(f"KGC Link: Link to '[[{link_target}]]' for '{relation_label}' is not canonical. Expected: '[[{canonical_link_target}]]' at line {line_num + 1}.")
        
        # Check for prohibited display text in wiki-links (e.g., [[Link | Display Text]])
        if '|' in link_target: 
            errors.append(f"KGC Link: Link '[[{link_target}]]' for '{relation_label}' contains prohibited display text. Display text is not allowed in wiki-links.")


        target_note_meta = next((n for n in all_notes_metadata if vault_utils.get_canonical_title(n.get('title')) == canonical_link_target), None)
        if not target_note_meta:
            errors.append(f"KGC Link: Link to missing note '[[{link_target}]]' for '{relation_label}' at line {line_num + 1}.")
        else:
            if expected_type != 'Any' and target_note_meta.get('type') != expected_type: 
                errors.append(f"KGC Link: Link to '[[{link_target}]]' for '{relation_label}' is of type '{target_note_meta.get('type')}', but expected '{expected_type}' at line {line_num + 1}.")
            
            if expected_link_canonical and canonical_link_target != expected_link_canonical:
                errors.append(f"KGC Link: Link to '[[{link_target}]]' for '{relation_label}' does not match the '{relation_label}' specified in YAML metadata ('{expected_link_canonical}') at line {line_num + 1}.")

        explanation_text = link_line[link_match.end():].strip()
        # Validator.py enforces a minimum of 5 words for KGC explanations
        if not explanation_text or len(explanation_text.split()) < 5: 
            errors.append(f"KGC Explanation: Missing or insufficient explanation (min 5 words) for link '{relation_label}: [[{link_target}]]' at line {line_num + 1}. Explanation: '{explanation_text}'")

    def _get_section_content(section_heading_text: str, current_kgc_content: str, search_start_idx: int):
        heading_pattern = re.compile(rf"^(##|###|####)\s+{re.escape(section_heading_text)}\s*$", re.MULTILINE)
        match = heading_pattern.search(current_kgc_content, search_start_idx)
        if not match:
            return None, -1, -1 

        start_idx = match.end()
        next_heading_pattern = re.compile(r"^\s*(#+)\s+.*$", re.MULTILINE)
        next_match = next_heading_pattern.search(current_kgc_content, start_idx)
        
        end_idx = next_match.start() if next_match else len(current_kgc_content)
        
        return current_kgc_content[start_idx:end_idx], match.start(), match.end()


    kgc_section_search_offset = 0

    unit_parents_section_content, section_rel_start_idx, section_rel_end_idx = _get_section_content("Unit Hub and Parents", kgc_section_content, kgc_section_search_offset)

    if not unit_parents_section_content:
        errors.append(f"Structure: Missing the mandatory '## Unit Hub and Parents' section within 'Knowledge Graph Connections'.")
    else:
        kgc_section_search_offset = section_rel_end_idx 
        expected_links_found = []
        
        unit_hub_pattern = re.compile(r"^(###)\s+Unit Hub:\s*\[\[([^\]]+?)\]\]\s*(.*)$", re.MULTILINE)
        unit_hub_match = unit_hub_pattern.search(unit_parents_section_content)
        
        if not unit_hub_match:
            errors.append(f"KGC: '## Unit Hub and Parents' section is missing '### Unit Hub: [[...]]' heading.")
        else:
            _validate_kgc_link(unit_hub_match.group(0), meta_unit_canonical, 'Unit', 'Unit Hub', kgc_match.start() + unit_hub_match.start() + 1)
            expected_links_found.append('Unit Hub')

        if note_type in ["Core", "Supporting"]:
            foundational_parent_pattern = re.compile(r"^(###)\s+Foundational Parent:\s*\[\[([^\]]+?)\]\]\s*(.*)$", re.MULTILINE)
            foundational_parent_match = foundational_parent_pattern.search(unit_parents_section_content, unit_hub_match.end() if unit_hub_match else 0)
            if not foundational_parent_match:
                errors.append(f"KGC: Note (type: {note_type}) - '## Unit Hub and Parents' section is missing '### Foundational Parent: [[...]]' heading.")
            else:
                _validate_kgc_link(foundational_parent_match.group(0), meta_parent_canonical if note_type == "Core" else "", 'Foundational', 'Foundational Parent', kgc_match.start() + foundational_parent_match.start() + 1)
                expected_links_found.append('Foundational Parent')

        if note_type == "Supporting":
            core_parent_pattern = re.compile(r"^(###)\s+Core Parent:\s*\[\[([^\]]+?)\]\]\s*(.*)$", re.MULTILINE)
            search_start_for_core_parent = 0
            if unit_hub_match: search_start_for_core_parent = max(search_start_for_core_parent, unit_hub_match.end())
            if foundational_parent_match: search_start_for_core_parent = max(search_start_for_core_parent, foundational_parent_match.end())

            core_parent_match = core_parent_pattern.search(unit_parents_section_content, search_start_for_core_parent)
            if not core_parent_match:
                errors.append(f"KGC: Note (type: {note_type}) - '## Unit Hub and Parents' section is missing '### Core Parent: [[...]]' heading.")
            else:
                _validate_kgc_link(core_parent_match.group(0), meta_parent_canonical, 'Core', 'Core Parent', kgc_match.start() + core_parent_match.start() + 1)
                expected_links_found.append('Core Parent')

        all_kgc_links_in_section = re.findall(r"^(###)\s*(.*?):\s*\[\[([^\]]+?)\]\]\s*(.*)$", unit_parents_section_content, re.MULTILINE)
        if len(all_kgc_links_in_section) != len(expected_links_found):
            errors.append(f"KGC: '## Unit Hub and Parents' section contains unexpected or extra links. Expected {len(expected_links_found)}, found {len(all_kgc_links_in_section)}.")

    concepts_built_section_content, section_rel_start_idx, section_rel_end_idx = _get_section_content("Concepts Built Upon This", kgc_section_content, kgc_section_search_offset)
    if concepts_built_section_content is not None: 
        kgc_section_search_offset = section_rel_end_idx 


    if note_type == "Supporting":
        if concepts_built_section_content and concepts_built_section_content.strip(): 
            errors.append(f"KGC: Note (type: Supporting) - '## Concepts Built Upon This' section should be empty.")
    elif note_type in ["Foundational", "Core"]:
        if not concepts_built_section_content:
            errors.append(f"KGC: Note (type: {note_type}) - Missing mandatory '## Concepts Built Upon This' section.")
        else:
            direct_child_links: List[Tuple[str, str, str, int]] = [] 
            for m in re.finditer(r"^(###)\s+Direct Child:\s*\[\[([^\]]+?)\]\]\s*(.*)$", concepts_built_section_content, re.MULTILINE):
                direct_child_links.append((m.group(0), m.group(2).strip(), m.group(3).strip(), kgc_match.start() + section_rel_start_idx + m.start() + 1))
            
            prev_link_target = ""
            for full_line, link_target, explanation, line_num in direct_child_links:
                expected_child_type = "Core" if note_type == "Foundational" else "Supporting"
                _validate_kgc_link(full_line, '', expected_child_type, 'Direct Child', line_num)
                
                if link_target < prev_link_target:
                    errors.append(f"KGC Order: Direct Child link '[[{link_target}]]' at line {line_num + 1} is out of alphabetical order (should be after '[[{prev_link_target}]]').")
                prev_link_target = link_target


    broader_context_section_content, section_rel_start_idx, section_rel_end_idx = _get_section_content("Broader Context", kgc_section_content, kgc_section_search_offset)
    if broader_context_section_content is not None:
         kgc_section_search_offset = section_rel_end_idx 


    if not broader_context_section_content:
        errors.append(f"Structure: Missing the mandatory '## Broader Context' section within 'Knowledge Graph Connections'.")
    else:
        contrasting_concepts_pattern = re.compile(r"^(###)\s+Contrasting Concepts\s*$", re.MULTILINE)
        contrasting_match = contrasting_concepts_pattern.search(broader_context_section_content)
        
        if not contrasting_match:
            errors.append(f"KGC: '## Broader Context' section is missing '### Contrasting Concepts' heading.")
        else:
            contrasting_section_content = broader_context_section_content[contrasting_match.end():]
            next_heading_or_end_match = re.search(r"^\s*(?:#+)\s*.*$", contrasting_section_content, re.MULTILINE)
            if next_heading_or_end_match:
                contrasting_section_content = contrasting_section_content[:next_heading_or_end_match.start()]

            contrasting_links: List[Tuple[str, str, str, int]] = []
            for m in re.finditer(r"^(####)\s+Contrasting:\s*\[\[([^\]]+?)\]\]\s*(.*)$", contrasting_section_content, re.MULTILINE):
                contrasting_links.append((m.group(0), m.group(2).strip(), m.group(3).strip(), kgc_match.start() + section_rel_start_idx + contrasting_match.start() + m.start() + 1))

            prev_link_target = ""
            for full_line, link_target, explanation, line_num in contrasting_links:
                _validate_kgc_link(full_line, '', 'Any', 'Contrasting', line_num) 
                if link_target < prev_link_target:
                    errors.append(f"KGC Order: Contrasting link '[[{link_target}]]' at line {line_num + 1} is out of alphabetical order (should be after '[[{prev_link_target}]]').")
                prev_link_target = link_target

        related_concepts_pattern = re.compile(r"^(###)\s+Related Concepts\s*$", re.MULTILINE)
        search_start_for_related = contrasting_match.end() if contrasting_match else 0
        related_match = related_concepts_pattern.search(broader_context_section_content, search_start_for_related)
        
        if not related_match:
            errors.append(f"KGC: '## Broader Context' section is missing '### Related Concepts' heading.")
        else:
            related_section_content = broader_context_section_content[related_match.end():]
            related_links: List[Tuple[str, str, str, int]] = []
            for m in re.finditer(r"^(####)\s+Related:\s*\[\[([^\]]+?)\]\]\s*(.*)$", related_section_content, re.MULTILINE):
                related_links.append((m.group(0), m.group(2).strip(), m.group(3).strip(), kgc_match.start() + section_rel_start_idx + related_match.start() + m.start() + 1))

            prev_link_target = ""
            for full_line, link_target, explanation, line_num in related_links:
                _validate_kgc_link(full_line, '', 'Any', 'Related', line_num) 
                if link_target < prev_link_target:
                    errors.append(f"KGC Order: Related link '[[{link_target}]]' at line {line_num + 1} is out of alphabetical order (should be after '[[{prev_link_target}]]').")
                prev_link_target = link_target
    return errors


def validate_questions_note(body_content: str, meta: Dict[str, Any], all_notes_metadata: List[Dict[str, Any]]) -> List[str]:
    """
    Validates the specific structure of a 'Questions' type note.
    Returns a list of errors.
    """
    errors: List[str] = []
    note_type = meta.get("type", "Unknown")
    note_title = meta.get("title", "Untitled_Note")

    if note_type != "Questions":
        return errors 

    unit_hub_h1_pattern = re.compile(r"^#\s*\[\[([^\]]+?)\]\] Questions\s*$", re.MULTILINE)
    unit_hub_h1_match = unit_hub_h1_pattern.search(body_content)

    if not unit_hub_h1_match:
        errors.append(f"Primary H1 heading is missing the mandatory '# [[Unit_Hub_Title]] Questions'.")
        return errors 

    unit_hub_link = unit_hub_h1_match.group(1).strip()
    canonical_unit_hub_link = vault_utils.get_canonical_title(unit_hub_link)

    if not canonical_unit_hub_link == unit_hub_link:
        errors.append(f"Unit Hub link '[[{unit_hub_link}]]' in H1 heading is not canonical. Expected: '[[{canonical_unit_hub_link}]]'.")

    unit_hub_exists_and_type_correct = any(vault_utils.get_canonical_title(n.get("title")) == canonical_unit_hub_link and n.get("type") == "Unit" for n in all_notes_metadata)
    if not unit_hub_exists_and_type_correct:
        errors.append(f"Unit Hub link '[[{unit_hub_link}]]' in H1 heading refers to a non-existent or non-Unit type note.")

    course_name = meta.get('course', 'Unsorted_Course')
    expected_note_title_start = f"{vault_utils.get_canonical_title(course_name)}_{canonical_unit_hub_link.replace('_Hub', '')}_Possible_Questions"
    if not note_title.startswith(expected_note_title_start):
        errors.append(f"Note title '{note_title}' does not match the expected format based on unit hub '{unit_hub_link}'. Expected to start with '{expected_note_title_start}'.")


    questions_content_after_h1 = body_content[unit_hub_h1_match.end():]
    
    questions_section_search_offset = 0

    foundational_h2_pattern = re.compile(r"^##\s*Foundational Concepts:\s*$", re.MULTILINE)
    foundational_h2_match = foundational_h2_pattern.search(questions_content_after_h1, questions_section_search_offset)

    if not foundational_h2_match:
        errors.append(f"Missing the mandatory '## Foundational Concepts:' section.")
    else:
        questions_section_search_offset = foundational_h2_match.end() 
        foundational_section_content_raw = questions_content_after_h1[foundational_h2_match.end():]
        next_h2_or_end_match = re.search(r"^\s*##\s*.*$", foundational_section_content_raw, re.MULTILINE)
        if next_h2_or_end_match:
            foundational_section_content = foundational_section_content_raw[:next_h2_or_end_match.start()]
        else:
            foundational_section_content = foundational_section_content_raw
        
        errors.extend(_validate_concept_questions_section(
            section_content=foundational_section_content,
            note_title=note_title,
            expected_heading_level="###",
            expected_concept_type="Foundational",
            all_notes_metadata=all_notes_metadata,
            section_start_line_in_body=unit_hub_h1_match.start() + foundational_h2_match.start() + 1 
        ))

    core_h2_pattern = re.compile(r"^##\s*Core Concepts building on \[\[([^\]]+?)\]\]:\s*$", re.MULTILINE)
    core_h2_match = core_h2_pattern.search(questions_content_after_h1, questions_section_search_offset)

    if not core_h2_match:
        errors.append(f"Missing the mandatory '## Core Concepts building on [[Foundational_Concept_Title]]:' section.")
    else:
        questions_section_search_offset = core_h2_match.end() 
        core_parent_link = core_h2_match.group(1).strip()
        canonical_core_parent_link = vault_utils.get_canonical_title(core_parent_link)
        
        if not canonical_core_parent_link == core_parent_link:
            errors.append(f"Core parent link '[[{core_parent_link}]]' in H2 heading is not canonical. Expected: '[[{canonical_core_parent_link}]]'.")
        
        core_parent_exists_and_type_correct = any(vault_utils.get_canonical_title(n.get("title")) == canonical_core_parent_link and n.get("type") == "Foundational" for n in all_notes_metadata)
        if not core_parent_exists_and_type_correct:
            errors.append(f"Core parent link '[[{core_parent_link}]]' in H2 heading refers to a non-existent or non-Foundational type note.")

        core_section_content_raw = questions_content_after_h1[core_h2_match.end():]
        next_heading_or_end_match = re.search(r"^\s*(?:##|####)\s*.*$", core_section_content_raw, re.MULTILINE)
        if next_h2_or_end_match:
            core_section_content = core_section_content_raw[:next_h2_or_end_match.start()]
        else:
            core_section_content = core_section_content_raw

        errors.extend(_validate_concept_questions_section(
            section_content=core_section_content,
            note_title=note_title,
            expected_heading_level="###",
            expected_concept_type="Core",
            all_notes_metadata=all_notes_metadata,
            section_start_line_in_body=unit_hub_h1_match.start() + core_h2_match.start() + 1
        ))
    
    supporting_h4_pattern = re.compile(r"^####\s*Supporting Concepts for \[\[([^\]]+?)\]\]:\s*$", re.MULTILINE)
    supporting_h4_match = supporting_h4_pattern.search(questions_content_after_h1, questions_section_search_offset)

    if not supporting_h4_match:
        errors.append(f"Missing the mandatory '#### Supporting Concepts for [[Core_Concept_Title]]:' section.")
    else:
        questions_section_search_offset = supporting_h4_match.end() 
        supporting_parent_link = supporting_h4_match.group(1).strip()
        canonical_supporting_parent_link = vault_utils.get_canonical_title(supporting_parent_link)
        
        if not canonical_supporting_parent_link == supporting_parent_link:
            errors.append(f"Supporting parent link '[[{supporting_parent_link}]]' in H4 heading is not canonical. Expected: '[[{canonical_supporting_parent_link}]]'.")
        
        supporting_parent_exists_and_type_correct = any(vault_utils.get_canonical_title(n.get("title")) == canonical_supporting_parent_link and n.get("type") == "Core" for n in all_notes_metadata)
        if not supporting_parent_exists_and_type_correct:
            errors.append(f"Supporting parent link '[[{supporting_parent_link}]]' in H4 heading refers to a non-existent or non-Core type note.")

        supporting_section_content = questions_content_after_h1[supporting_h4_match.end():]
        
        errors.extend(_validate_concept_questions_section(
            section_content=supporting_section_content,
            note_title=note_title,
            expected_heading_level="#####",
            expected_concept_type="Supporting",
            all_notes_metadata=all_notes_metadata,
            section_start_line_in_body=unit_hub_h1_match.start() + supporting_h4_match.start() + 1
        ))

    return errors


def validate_single_note(raw_note_content: str, all_notes_metadata: List[Dict[str, Any]]) -> Dict[str, List[str]]:
    """
    Validates a single note for core YAML errors and basic markdown body structure.
    Returns a dictionary of categorized errors.
    """
    validation_results: Dict[str, List[str]] = {
        "YAML Errors": [],
        "H1 Headings Errors": [],
        "Markdown Formatting Errors": [],
        "Wiki-Link Errors": [],
        "Code & LaTeX Block Errors": [],
        "Markdown Table Errors": [],
        "Knowledge Graph Connections Errors": [],
        "Questions Note Structure Errors": [],
        "Warnings": [],
        "System Errors": [] # Added System Errors for internal issues
    }

    # 1. YAML Extraction & Initial Error Check
    meta, body_content, yaml_error_occurred = vault_utils.extract_yaml_and_content(raw_note_content)

    note_title_for_log = meta.get("title", "Untitled_Note")
    note_type_for_log = meta.get("type", "Unknown")

    if yaml_error_occurred:
        validation_results["YAML Errors"].append(f"YAML Parse: Malformed YAML frontmatter. Content snippet: {raw_note_content[:200]}...")
        return validation_results 

    if not meta:
        validation_results["YAML Errors"].append(f"YAML Parse: YAML frontmatter is empty or could not be parsed as a dictionary.")
        if not body_content.strip():
            validation_results["YAML Errors"].append(f"Content: Note is completely empty (no YAML, no content).")
        return validation_results 

    # 2. Validate YAML Frontmatter
    yaml_errors_list = validate_yaml_frontmatter(meta, raw_note_content, note_title_for_log, note_type_for_log, all_notes_metadata)
    for err_msg in yaml_errors_list:
        if err_msg.startswith("Warning:"):
            validation_results["Warnings"].append(f"YAML: {err_msg.replace('Warning: ', '')}")
        else:
            validation_results["YAML Errors"].append(f"YAML: {err_msg}")
    
    # 3. Validate Markdown Body Structure (H1s, blank lines, separators) - uses raw body_content
    if body_content.strip(): 
        body_structure_errors = validate_markdown_body_structure(body_content, meta)
        for err_msg in body_structure_errors:
            if err_msg.startswith("H1 Naming:") or err_msg.startswith("Structure:"):
                validation_results["H1 Headings Errors"].append(err_msg)
            elif err_msg.startswith("Formatting:") or err_msg.startswith("Content:"): 
                validation_results["Markdown Formatting Errors"].append(err_msg)
            elif err_msg.startswith("Internal Validator Error:"): # Critical internal errors
                validation_results["System Errors"].append(err_msg) # New category for internal issues
            else:
                validation_results["Markdown Formatting Errors"].append(err_msg) 

    # Apply `process_code_blocks` before further content-based validation (e.g., wiki-links, tables)
    # NOTE: `validate_code_latex_blocks` and `validate_markdown_tables` run on `body_content` (raw) before `process_code_blocks`
    # to catch raw markers/emojis BEFORE they are processed/converted by vault_utils.
    # Wiki-link validation needs the processed content to correctly check for [[Link_Target | Display Text]] issues AFTER display text is stripped.

    # 4. Validate Wiki-Links (Increment 3) - uses processed body_content (after vault_utils.process_code_blocks)
    # It's crucial for this to run *after* process_code_blocks to detect the output of the display text stripping.
    processed_body_content_for_links = vault_utils.process_code_blocks(body_content)
    wiki_link_errors = validate_wiki_links(processed_body_content_for_links, all_notes_metadata, note_title_for_log)
    for err_msg in wiki_link_errors:
        validation_results["Wiki-Link Errors"].append(err_msg)

    # 5. Validate Code and LaTeX Blocks (Increment 4) - uses raw body_content
    # This must run on raw body_content to detect prohibited raw ``` or malformed custom markers and callouts.
    code_latex_errors = validate_code_latex_blocks(body_content, meta)
    for err_msg in code_latex_errors:
        if err_msg.startswith("Code Block:") or err_msg.startswith("LaTeX Block:") or err_msg.startswith("LaTeX Formatting:") or err_msg.startswith("Content:") or err_msg.startswith("Formatting:"): # Added Formatting: for callouts
            validation_results["Code & LaTeX Block Errors"].append(err_msg)
        else:
            validation_results["Code & LaTeX Block Errors"].append(err_msg) 

    # 6. Validate Markdown Tables (Increment 5) - uses raw body_content
    # This must run on raw body_content to detect emojis within tables before process_code_blocks removes them.
    markdown_table_errors = validate_markdown_tables(body_content, note_title_for_log)
    for err_msg in markdown_table_errors:
        if err_msg.startswith("Table Formatting:") or err_msg.startswith("Table:"):
            validation_results["Markdown Table Errors"].append(err_msg)
        else:
            validation_results["Markdown Table Errors"].append(err_msg)

    # 7. Validate Knowledge Graph Connections (Increment 6) - uses processed body_content (for links)
    kgc_errors = validate_knowledge_graph_connections(processed_body_content_for_links, meta, all_notes_metadata)
    for err_msg in kgc_errors:
        if err_msg.startswith("Structure:") or err_msg.startswith("KGC Link:") or err_msg.startswith("KGC Explanation:") or err_msg.startswith("KGC Order:") or err_msg.startswith("KGC:"):
            validation_results["Knowledge Graph Connections Errors"].append(err_msg)
        else:
            validation_results["Knowledge Graph Connections Errors"].append(err_msg)

    # 8. Validate Questions Note Specific Structure (Increment 7) - uses processed body_content (for links)
    questions_note_errors = validate_questions_note(processed_body_content_for_links, meta, all_notes_metadata)
    for err_msg in questions_note_errors:
        validation_results["Questions Note Structure Errors"].append(err_msg)

    return validation_results


def main():
    print("=== Obsidian Knowledge Architect (OKA) Validator (All Increments Active) ===\n")

    all_notes_metadata_from_vault = vault_utils.load_all_notes_metadata(vault_utils.VAULT_BASE_PATH)

    if not all_notes_metadata_from_vault:
        print(f"No notes found in the vault at '{vault_utils.VAULT_BASE_PATH}'. Please ensure the vault path is correct and contains .md files.\n")
        return

    all_validation_reports: List[Dict[str, Any]] = []

    print(f"--- Validating {len(all_notes_metadata_from_vault)} Notes in Vault ---\n")
    for note_meta in all_notes_metadata_from_vault:
        file_path = note_meta.get('_file_path')
        note_title_for_log = note_meta.get('title', file_path.stem if file_path else 'Unknown_Title')

        if not file_path or not isinstance(file_path, Path):
            report = {
                "file_path": "N/A",
                "note_title": note_title_for_log,
                "is_valid": False,
                "has_errors": True,
                "has_warnings": False,
                "error_categories": {
                    "System Errors": [f"Skipping note with missing or invalid file path in metadata: {note_meta}."]
                }
            }
            all_validation_reports.append(report)
            continue

        raw_note_content = ""
        try:
            raw_note_content = vault_utils.read_file(file_path)
        except IOError as e:
            report = {
                "file_path": str(file_path),
                "note_title": note_title_for_log,
                "is_valid": False,
                "has_errors": True,
                "has_warnings": False,
                "error_categories": {
                    "System Errors": [f"File I/O: Could not read file '{file_path.name}'. Error: {e}"]
                }
            }
            all_validation_reports.append(report)
            continue

        categorized_errors = validate_single_note(raw_note_content, all_notes_metadata_from_vault)
        
        has_errors = any(len(v) > 0 for k, v in categorized_errors.items() if k != "Warnings" and k != "System Errors") # Exclude warnings from 'errors' count
        has_warnings = len(categorized_errors.get("Warnings", [])) > 0
        has_system_errors = len(categorized_errors.get("System Errors", [])) > 0


        report = {
            "file_path": str(file_path),
            "note_title": note_title_for_log,
            "is_valid": not has_errors and not has_warnings and not has_system_errors,
            "has_errors": has_errors or has_system_errors, # Any real error makes it has_errors
            "has_warnings": has_warnings,
            "error_categories": categorized_errors
        }
        all_validation_reports.append(report)
    
    # --- Print Formatted Reports ---
    overall_errors_found = False
    notes_with_errors_count = 0
    notes_with_warnings_only_count = 0
    notes_fully_compliant_count = 0

    for report in all_validation_reports:
        print(f"--- Report for '{report['note_title']}' ({Path(report['file_path']).name if report['file_path'] != 'N/A' else 'N/A'}) ---")
        
        if report['has_errors']:
            print("Status: ❌ INVALID\n")
            overall_errors_found = True
            notes_with_errors_count += 1
        elif report['has_warnings']:
            print("Status: ✅ VALID with warnings\n")
            notes_with_warnings_only_count += 1
        else:
            print("Status: ✅ FULLY COMPLIANT\n")
            notes_fully_compliant_count += 1
        
        # Print errors
        found_any_category_errors = False
        for category, errors_list in report['error_categories'].items():
            if errors_list and category != "Warnings":
                if not found_any_category_errors:
                    print("Errors Found:")
                    found_any_category_errors = True
                print(f"  - **{category}:**")
                for err_msg in errors_list:
                    print(f"    - {err_msg}")
        if found_any_category_errors:
            print("") # Newline after errors

        # Print warnings
        if report['error_categories'].get('Warnings'):
            print("Warnings Found:")
            for warn_msg in report['error_categories']['Warnings']:
                print(f"  - {warn_msg}")
            print("") # Newline after warnings
        
        if not report['has_errors'] and not report['has_warnings']:
            print("  No issues found.")
            print("") 
        
    print("--- Validation Summary ---\n")
    print(f"Total Notes Validated: {len(all_notes_metadata_from_vault)}")
    print(f"Total Notes with Errors: {notes_with_errors_count}")
    print(f"Total Notes with Warnings (no errors): {notes_with_warnings_only_count}")
    print(f"Total Notes Fully Compliant: {notes_fully_compliant_count}\n")

    if not overall_errors_found and notes_with_warnings_only_count == 0:
        print("Overall Result: ✅ All notes passed validation with no errors or warnings. All increments fully compliant!\n")
    elif not overall_errors_found and notes_with_warnings_only_count > 0:
        print("Overall Result: ⚠️ Validation completed with warnings. All critical errors resolved, but minor issues remain.\n")
    else:
        print("Overall Result: ❌ Validation completed with errors. Please review the report above for details.\n")


if __name__ == "__main__":
    main()