const fs = require('fs');
const path = require('path');

// This script generates the update.json for Tauri's auto-updater.
// It assumes that the binaries and their .sig files are already uploaded to GitHub Releases.

const ORG = 'YOUR_ORG';
const REPO = 'ater';
const VERSION = process.argv[2] || '0.1.0'; // Pass version as argument

const platforms = {
  'darwin-aarch64': {
    signature: '', // Read from files in production
    extension: '.app.tar.gz'
  },
  'darwin-x86_64': {
    signature: '',
    extension: '.app.tar.gz'
  },
  'linux-x86_64': {
    signature: '',
    extension: '.AppImage.tar.gz'
  },
  'windows-x86_64': {
    signature: '',
    extension: '.msi.zip'
  }
};

const updateJson = {
  version: VERSION,
  notes: `Release ${VERSION}`,
  pub_date: new Date().toISOString(),
  platforms: {}
};

// In a real CI environment, we would read the .sig files generated by Tauri
// and populate the 'signature' and 'url' fields.
Object.keys(platforms).forEach(platform => {
  const { extension } = platforms[platform];
  const artifactName = `Ater_${VERSION}_${platform}${extension}`;
  
  updateJson.platforms[platform] = {
    signature: fs.existsSync(`./artifacts/${artifactName}.sig`) 
      ? fs.readFileSync(`./artifacts/${artifactName}.sig`, 'utf-8') 
      : 'PLACEHOLDER_SIGNATURE',
    url: `https://github.com/${ORG}/${REPO}/releases/download/v${VERSION}/${artifactName}`
  };
});

fs.writeFileSync('update.json', JSON.stringify(updateJson, null, 2));
console.log('✅ update.json generated successfully!');
