import os
from datetime import datetime

BASE_ACADEMIC = "/Users/dabodestroyer/code/Antigravity/LifeOs/Obsidian_Vault/2-Academic/Year II/Semester I"
HUB_DIR = "/Users/dabodestroyer/code/Antigravity/LifeOs/Obsidian_Vault/3-Database/06 - Study Planner"

SEMESTER = "[[Autumn 2025]]" # Current semester according to user screenshot

def create_hub(course_name, unit_folder_name):
    # Sanitize title for filename
    hub_title = f"{unit_folder_name.replace(' ', '_')}_Hub"
    hub_path = os.path.join(HUB_DIR, f"{hub_title}.md")
    
    if os.path.exists(hub_path):
        return
    
    # Extract unit number
    parts = unit_folder_name.split(' ', 1)
    unit_num = parts[0] if parts[0].isdigit() else ""
    
    new_fm = {
        "title": hub_title,
        "type": "Hub",
        "course": f"[[{course_name}]]",
        "semester": SEMESTER,
        "unit": unit_num,
        "status": "Not Started",
        "confidence": "",
        "study_date": "",
        "generated": "true",
        "last_synced": datetime.now().isoformat(),
        "last_edited_time": datetime.now().isoformat(),
        "last_edited_by": "LifeOs AI Agent"
    }
    
    content = f"# {unit_folder_name}\n\n"
    content += "## 📂 Notes\n"
    # Find notes for this unit in the academic path
    unit_rel_path = f"2-Academic/Year II/Semester I/{course_name}/{unit_folder_name}"
    content += f"All knowledge assets for this unit are stored in: [[{unit_rel_path}]]\n\n"
    content += f"---\nGenerated by LifeOs for high-fidelity sync."
    
    with open(hub_path, 'w', encoding='utf-8') as f:
        f.write("---\n")
        for k, v in new_fm.items():
            f.write(f"{k}: \"{v}\"\n")
        f.write("---\n\n")
        f.write(content)
    print(f"Created Hub: {hub_path}")

def main():
    if not os.path.exists(HUB_DIR):
        os.makedirs(HUB_DIR)
        
    for course_name in os.listdir(BASE_ACADEMIC):
        course_path = os.path.join(BASE_ACADEMIC, course_name)
        if not os.path.isdir(course_path):
            continue
            
        for folder in os.listdir(course_path):
            if folder == "_Combined" or folder == ".DS_Store":
                continue
            unit_path = os.path.join(course_path, folder)
            if os.path.isdir(unit_path):
                create_hub(course_name, folder)

if __name__ == "__main__":
    main()
