# src/domains/oka/taxonomy.py

"""
The definitive structural map of the OKA Pantheon.
Defines the hierarchical relationship between disciplines and domain keys.
"""

CANONICAL_TAXONOMY = {
    "NATURAL_SCIENCES": {
        "PHYSICS": ["PHYS-MECHANICS", "PHYS-QUANTUM", "PHYS-THERMO", "PHYS-ELECTRO", "PHYS-ASTRO"],
        "CHEMISTRY": ["CHEM-ORGANIC", "CHEM-INORGANIC", "CHEM-PHYSICAL", "CHEM-ANALYTICAL"],
        "BIOLOGY": ["BIO-GENETICS", "BIO-CELL", "BIO-ECOLOGY", "BIO-MOLECULAR", "BIO-EVOLUTION"],
        "EARTH_SCIENCE": ["EARTH-GEOLOGY", "EARTH-METEOROLOGY", "EARTH-OCEANOGRAPHY", "EARTH-CLIMATE"],
        "ASTRONOMY": ["ASTRONOMY", "COSMOLOGY", "ASTROPHYSICS"],
    },
    "FORMAL_SCIENCES": {
        "MATHEMATICS": ["MATH-ALGEBRA", "MATH-CALCULUS", "MATH-DISCRETE", "MATH-STATS", "MATH-PURE", "MATH-GEOMETRY"],
        "COMPUTER_SCIENCE": ["CS-GENERAL", "CS-WEB-DEV", "CS-DATA-SYSTEMS", "CS-AI-ML", "CS-CYBER-SEC", "CS-NETWORKS", "CS-OS"],
        "LOGIC": ["LOGIC-FORMAL", "MATH-LOGIC"],
    },
    "SOCIAL_SCIENCES": {
        "ECONOMICS": ["ECON-MICRO", "ECON-MACRO", "ECON-FINANCE", "ECON-METRICS", "ECON-BEHAVIORAL", "ECON-HISTORY"],
        "POLITICAL_SCIENCE": ["POLI-SCIENCE", "POLI-THEORY", "POLI-RELATIONS", "POLI-POLICY"],
        "SOCIOLOGY": ["SOCIOLOGY", "SOC-STRATIFICATION", "SOC-CULTURE", "SOC-DEMOGRAPHICS"],
        "PSYCHOLOGY": ["PSYCHOLOGY", "PSYCH-COGNITIVE", "PSYCH-CLINICAL", "PSYCH-DEVELOPMENTAL", "PSYCH-BEHAVIORAL"],
        "ANTHROPOLOGY": ["ANTHROPOLOGY", "ANTHRO-ETHNOGRAPHY", "ANTHRO-ARCHAEOLOGY"],
        "HISTORY": ["HISTORY-GENERAL", "HIST-ANCIENT", "HIST-MODERN", "HIST-MEDIEVAL", "HIST-REGIONAL"],
        "GEOGRAPHY": ["GEOGRAPHY", "GEO-PHYSICAL", "GEO-HUMAN", "GEO-GIS"],
        "LAW": ["LAW-GENERAL", "LAW-CONSTITUTIONAL", "LAW-CONTRACT", "LAW-CRIMINAL", "LAW-TORT", "LAW-INTERNATIONAL"],
    },
    "HUMANITIES": {
        "PHILOSOPHY": ["PHILOSOPHY", "PHIL-ETHICS", "PHIL-METAPHYSICS", "PHIL-EPISTEMOLOGY", "PHIL-AESTHETICS"],
        "LINGUISTICS": ["LINGUISTICS", "LING-SYNTAX", "LING-PHONOLOGY", "LING-SEMANTICS"],
        "LITERATURE": ["LITERATURE", "LIT-FICTION", "LIT-POETRY", "LIT-DRAMA", "LIT-CRITICISM"],
        "ARTS": ["ARTS-VISUAL", "ARTS-PERFORMING", "ARTS-HISTORY", "ARTS-THEORY"],
        "RELIGION": ["RELIGION", "REL-THEOLOGY", "REL-HISTORY", "REL-COMPARATIVE"],
    },
    "APPLIED_SCIENCES": {
        "ENGINEERING": ["ENGINEERING-MECH", "ENGINEERING-ELEC", "ENGINEERING-CIVIL", "ENGINEERING-CHEM", "ENGINEERING-AERO", "ENGINEERING-SOFTWARE"],
        "MEDICINE": ["MEDICINE-GENERAL", "MED-ANATOMY", "MED-PHYSIOLOGY", "MED-PHARMA", "MED-SURGERY"],
        "BUSINESS": ["BUSINESS-FINANCE", "BIZ-MARKETING", "BIZ-STRATEGY", "BIZ-OPERATIONS", "BIZ-MANAGEMENT", "BIZ-ACCOUNTING"],
        "EDUCATION": ["EDUCATION", "EDU-PEDAGOGY", "EDU-CURRICULUM", "EDU-ASSESSMENT", "EDU-TECHNOLOGY"],
        "AGRICULTURE": ["AGRICULTURE", "AGRI-FARMING", "AGRI-CROP", "AGRI-LIVESTOCK"],
    },
    "ARTS_AND_SKILLS": {
        "MUSIC": ["MUSIC-THEORY", "MUSIC-HISTORY", "MUSIC-COMPOSITION", "MUSIC-PERFORMANCE"],
        "DESIGN": ["DESIGN-UX-UI", "DESIGN-GRAPHIC", "DESIGN-INDUSTRIAL", "DESIGN-FASHION"],
        "CRAFTSMANSHIP": ["CRAFTSMANSHIP", "CRAFT-WOOD", "CRAFT-METAL", "CRAFT-TEXTILE"],
    }
}

def get_all_domains():
    """Returns a flattened list of all valid domain keys in the taxonomy."""
    domains = []
    for cat in CANONICAL_TAXONOMY.values():
        for subcat in cat.values():
            domains.extend(subcat)
    return domains
